---
title: "CREAR UN PROYECTO EN RSTUDIO"
author: "HUAROTE AVALOS KEVIN"
format: html
editor: visual
---

## CONTEXTO

SEMANA 6: COMO LIMPIAR UNA DATA USANDO UNA COLUMNA ESPECIFICA

## PASO 1

```{r}
#DESCARGAMOS LA GUIA
```

## PASO 2

```{r}
#INGRESAMOS A LA SEMANA 6  Y ENTRAMOS AL LINK GIBHUB
```

## PASO 3

```{r}
#3: ENTRAMOS DONDE INDICA EN LA  PARTE DONDE DICE DATA
```

## PASO 4

```{r}
# 4:SELECCIONAMOS EL ARCHIVO CSV PARA Y DAMOS EN PARTE DE DESCARGA
```

## PASO 5

```{r}
#5: VEZ DESCAGADO BUSCAMOS  EN NUESTRO ESCRITORIO
```

## PASO 6

```{r}
#6: EN EL RSTUDIO HACEMOS CLIC EN IMPORT DATASET
```

## PASO 7

```{r}
#7:HACEMOS CLIC HASTA LA  PARTE FROM TEST (READR)
```

## PASO 8

```{r}
#8: HACEMOS CLIC EN LA PARTE BROWSE PARA BUSCAR EL DOCUMENTOS
```

## PASO 9

```{r}
#9: CARGAMOS EL DOCUMENTO QUE VAMOS A UTILIZAR
library(readr)
cirrosis_tarea <- read_csv("C:/Users/huaro/Downloads/cirrosis tarea.csv")
View(cirrosis_tarea)
```

## PASO 10

```{r}
#10: ANTES DE IMPORTAR EL DOCUMENTO COPIAMOS  EL CODIGO ABAJO QUE ESTA ABAJO PARA PODER  HACER UNA COPIA PARA NO DAÑAR EL DOCUMENTO  ORIGINAL

<- read_csv("C:/Users/huaro/Downloads/cirrosis tarea.csv")
```

## PASO 11

```{r}
#11: UNA VEZ IMPORTADO PONEMOS EL  SIGUIENTE CODIGO Y USANDO EL  COMANDO COPIADO ANTERIORMENTE
DATA<- read_csv("C:/Users/huaro/Downloads/cirrosis tarea.csv")
```

## PASO 11

```{r}
#12: SI SE HIZO BIEN APARECERA EL LA  PARTE DEL COSTADO UNA QUE DICE  DATA CON ESA TRABAJAREMOS
```

## PASO 13

```{r}
#13: USANDO EL SIGUIENTE COMANDO LO  USAREMOS PARA ELIMINAR DATOS NO  NECESARIOS O QUE TIENEN VALOR(SEGUN EL TITULO DE LA COLLUMNA A USAR)
data_limpia<-DATA[!is.na(DATA$Ascitis), ]
```

## PASO 14

```{r}
#14: UNA VEZ HECHO ESO APARECERA UNA QUE DICE DATA LIMPIA HACEMOS CLIC
```

## PASO 15

```{r}
#15: LISTO APARECE LA DATA LIMPIAR  CON EL VALOR TRABAJADO
```
